version: 2

jobs:
  test_node_8:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: yarn install
      - run: yarn build

  release:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: yarn install
      - run: yarn build
      - run: yarn semantic-release

workflows:
  version: 2
  test_and_release:
    jobs:
      - test_node_8
      - release:
          requires:
            - test_node_8
