version: 2

jobs:
  build_and_test:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: yarn install
      - run: yarn build

  release:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: yarn install
      - run: yarn semantic-release

workflows:
  version: 2
  test_and_release:
    jobs:
      - build_and_test
      - release:
          filters:
            only: master
          requires:
            - build_and_test
